// Reads .env at the project root and writes config.js (gitignored) for the
// background service worker to import. Run via `npm run generate-config`.

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const envPath = path.join(root, '.env');
const outPath = path.join(root, 'config.js');

if (!fs.existsSync(envPath)) {
  console.error('Missing .env file at project root. Create one with GEMINI_API_KEY=your-key');
  process.exit(1);
}

const env = Object.fromEntries(
  fs
    .readFileSync(envPath, 'utf8')
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#'))
    .map((line) => {
      const idx = line.indexOf('=');
      return [line.slice(0, idx).trim(), line.slice(idx + 1).trim()];
    }),
);

if (!env.GEMINI_API_KEY) {
  console.error('.env is missing GEMINI_API_KEY');
  process.exit(1);
}

const contents = `// Generated by scripts/generate-config.js from .env — do not edit directly, do not commit.
// This file is loaded only by background.js (service worker). Never exposed to UI pages.

export const GEMINI_API_KEY = '${env.GEMINI_API_KEY}';
`;

fs.writeFileSync(outPath, contents);
console.log('Wrote config.js from .env');
